coco:
  train: 
    root: /mnt/hdd-4tb/abhay/coco/train2017
    ann: /mnt/hdd-4tb/abhay/coco/annotations/stuff_train2017.json
  test:
    root: /mnt/hdd-4tb/abhay/coco/val2017
    ann: /mnt/hdd-4tb/abhay/coco/annotations/stuff_val2017.json