coco:
  train: 
    root: ../../data/coco/train2017
    ann: ../../data/coco/annotations/stuff_train2017.json
  test:
    root: ../../data/coco/val2017
    ann: ../../data/coco/annotations/stuff_val2017.json